<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ShipTracker</RootNamespace>
    <AssemblyName>ShipTracker</AssemblyName>
    <Product>ShipTracker</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ibdg.GMap.NET.WinForms" Version="2.1.8" />
  </ItemGroup>

</Project>
